# Generated by Django 6.0.5 on 2026-07-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsys', '0004_alter_user_address_alter_user_phone_number'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsys.user')),
            ],
        ),
    ]
