# Generated by Django 6.0.5 on 2026-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_key', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
