# Generated by Django 6.0.5 on 2026-07-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0003_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
